version: '3.8'

services:
  files:
    build: .
    ports:
      - "8003:8000"
    env_file:
      - .env
    volumes:
      - ./src:/src
    depends_on:
      - minio
    networks:
      - core_network

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - core_network

volumes:
  minio-data:

networks:
  core_network:
    external: true
